default_install_hook_types:
  - pre-commit
  - pre-push
  - commit-msg
# Stage names now match git hooks; requires pre-commit >= 3.2.0
default_stages:
  - post-checkout
  - post-merge
  - post-rewrite
  - pre-commit
  - pre-rebase

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Linting
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # Git tidy
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      # Security
      - id: detect-private-key
        stages:
          - pre-push

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "3.0.0"
    hooks:
      - id: shellcheck
        types: []
        types_or: [file, shell]
        files: (\.sh|\.bash)$
        args: ["-S", "warning"]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.1
    hooks:
      - id: terraform_providers_lock
        args:
          - --tf-init-args=-input=false
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
          - --tf-init-args=-input=false
          - --tf-init-args=-upgrade
      - id: terraform_tfsec
        stages:
          - pre-push
      - id: terraform_fmt
      - id: terraform_docs
        files: (\.tf|\.terraform\.lock\.hcl|\.terraform-docs\.yml|header\.md)$
        args:
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--path-to-file=README.md

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.2.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
        args: [feat, fix, update, chore, test]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
        stages:
          - pre-push

  - repo: https://github.com/python-jsonschema/check-jsonschema.git
    rev: 0.23.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
