# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

includes:
  terragrunt:
    taskfile: tasks/Terragrunt.taskfile.yaml
  dependencies:
    # dir: tasks/
    taskfile: tasks/Dependencies.taskfile.yaml

tasks:
  default:
    cmds:
      - task -l
      - |
        echo
        echo 'Please use the following env vars to change the default behavior:
          TG_REFRESH=true       # invalidate cache
          TG_YOLO=true          # auto-approve
        '
    silent: true
