---
- namespace:
    name: IAM-UserInfo
    description: Info about a created user
  tags:
    UserType:
      description: The type of user
      allowed_values:
        - human
        - robot
- namespace:
    name: K3s-NodeInfo
    description: K3s node informations
  tags:
    NodeRole:
      description: The K3s node role (master or worker)
      allowed_values:
        - master
        - worker
    # This is useful to flag the progress of the provisioning Ansible script
    NodeInitStatus:
      description: The status of the node initialization process
      allowed_values:
        - notstarted
        - starting
        - joining
        - succeeded
        - failed
# We don't have a K3s-ClusterConfig because we drop directly the config as a YAML with UserData. That's how we roll.
- namespace:
    name: K3s-ClusterSecrets
    description: K3s node configuration
  tags:
    agent-token:
      description: The Secret ID containing the token used by agents to join the cluster
    token:
      description: The Secret ID containing the token used by server to join the cluster
    etcd-s3-secret-key:
      description: The Secret ID containing an S3 Secret Key used to access the bucket where to store ETCD backups
