#ENC[AES256_GCM,data:ebb4JvlnCT0F/11I+P7IeNs/kMYQYCkRVozOuxbJi2cpYog=,iv:2nbDRBVDCFUd5HsC3VG3czG0nykSAinsaxuYNRqbefY=,tag:H1fEpgSJV8Oupl/tUuM8Fg==,type:comment]
do_token: ENC[AES256_GCM,data:5D0pZI9vNoub+mbJ1WAq85zYN2jURvzPcguvWQzQHudOegRMemZqoHxqfFPYYiNvVzuqG0MipLiq8bYrv3FmhhDKXx1afB0=,iv:sSOboZYmPensfPJ0U2d+o9Xpf/8LxwYI0v75lnz1fyk=,tag:6ftPQVe5eenVSBS6upWuLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-12T07:50:25Z"
    mac: ENC[AES256_GCM,data:gSG3KiVkZiJMVSFlp/T8h4MlhIRJUACidez9sG2hXVCKQiLmFsDngS7GSVFY0IrhayKSwX/kcD+X0dQuYD2yCUqRry5XQexc/Sj5YneN42WFe5vrZlyNEXbx2vLimYbi9brCr3LrBlNPdmSjhWUHCX9uNPtaDG64wZ8NK8lMKY4=,iv:Y4NSYcYJukRh4Ov9d/pTC3PGSQEsN8APpPUjleYhgBw=,tag:HrjZaTZsiEnWhBsM9QwOwA==,type:str]
    pgp:
        - created_at: "2023-05-08T06:48:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2fheYx7el0jAQ/+IhaLFr2hmR3wrurveRfv+13BtUf7uwsuWStR2UfVRqQT
            BkAug1CoTDOef6AqoaDYAXM/bzkD7ns2C84RqiddT6dj9t+dB5C6fKFiho7d0FtN
            4bidD73NWcfSPE7MWrQ8RUkzS3S+CrQdmk75p+K4VZE0nLzqCPkkCNwpcxzRL8bL
            CdsdE168iPIy5U3rCqJxpre/pSVaaR9J6IxAblagGyf5ur8+WeA6knJSbvkJyBmL
            orw+Z2IYBdmlYzKmSXfJLZ0ATukdU+URmfO7PDPV2FtLPTQlmt62D1UO3K3Jkc3S
            L53hwjwyi3tN4vzyDsqILbbEq9c6Y2Vjij6xu+mlehdJNE1gEC+tCIiyBP5CUzAc
            K90A5v8aDqEzxKclaX77uv2EliO3kwx5Eent9lDYBHO9gCOorWdIebCTSRhNxhxF
            l99cGbiZBZxp0D5oiuVKAEEmvhfnufdx3ugL7mWaqQLUMmH4ZMYx/6HkTYbn9Fab
            +4unOu2fD3RTEXvYk76NNFAJwQAPHeWcqkBazWU0+Sla1H+pUASR8goheWwmE2FB
            lIqYXF8+4ZkrJfQLyUOPBHIJ8arngOONY9koMqnGZyN65v0hQbgVpQp5wNFpw6tE
            juX1c1H5ij+9+T9r9LR7uWVwrQm8GorYq9HRJpCqFOXAjXTMTdvB30zXr+AXqaTS
            XgExcsrRJYIdYS/GBvQOZe6Sgfe/4iw4Phkg0DlxuNUL4mKtCQudIqmeGPnfkNda
            k5tSnHHrCptoklTCwfuaWpL9QAYCD7vibOgwEodIhK+giTS1rmUt6JF0a0d3Uyk=
            =e1oO
            -----END PGP MESSAGE-----
          fp: AF99E31FE58AD5C9EB027EB667E1798C7B7A5D23
    unencrypted_suffix: _unencrypted
    version: 3.7.3
